#!/bin/bash

set -e

PIP_OPTS="--break-system-packages"

pip3 install ${PIP_OPTS} /usr/lib/hobot_spdev/hobot_dnn*.whl
pip3 install ${PIP_OPTS} /usr/lib/hobot_spdev/hobot_vio*.whl
pip3 install ${PIP_OPTS} /usr/lib/hobot_spdev/hbm_runtime*.whl

ldconfig

exit 0
